
server:
  port: 9529

spring:
  application:
    name: nacos-feign

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848




#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
