#规划GateWay的服务端口
server:
  port: 9527
##规划gateWay注册到到nacos上的服务应用名称
spring:
  application:
    name: commons-api-gateway
  cloud:
    nacos:
      discovery:
        #gateway工程注册到nacos上的地址
        server-addr: 120.77.255.131:8848
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能，利用服务名进行路由
          lower-case-service-id: true # 设置路由的路径为小写的服务ID
      routes:
        - id: commons-routh    #路由的Id,没有固定的规则要求,建议配合服务名
#          uri: http://localhost:9001   #访问服务的真实地址
          uri: lb://server-consumer-nacos-discovery  #lb= loadblance 表示负载均衡  后面接的注册中心的服务名
          predicates:
            - Path=/order/payment/**
            #如果开启了动态路由，规则就会失效
            #- After=2020-12-04T12:44:12.206+08:00[Asia/Shanghai]
#            - Cookie=username,zzyy
#          filters:
#            - StripPrefix=1 # 移除前缀 youlai-auth
#        - id: youlai-admin
#          uri: lb://youlai-admin
#          predicates:
#            - Path=/youlai-admin/**
#          filters:
#            - StripPrefix=1
#  profiles:
#    active: xxxxx  # 具体的gateway配置


