server:
  port: 3344

spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          #uri: Github上的git仓库名字
          uri: https://github.com/xupeng0601/SpringCloud-xp
          ##搜索目录.这个目录指的是github上的目录
          search-paths: /config
      ##读取分支
      label: master
  #rabbit相关配置 15672是web管理界面的端口，5672是MQ访问的端口
  rabbitmq:
    host: 120.77.255.131
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

#rabbitmq相关设置 ，暴露 bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: "bus-refresh"