
server:
  port: 9527

spring:
  application:
    name: nacos-inventory
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://120.77.255.131:3306/nacos-practice?characterEncoding=utf-8&useSSl=false&serverTimeZone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: 120.77.255.131




