server:
  port: 8100

spring:
  application:
    name: cloud-hy-opfe-service #服务名

eureka:
  client:
    register-with-eureka: true #表示向注册中心注册自己 默认为true
    fetch-registry: true #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    service-url:
      defaultZone: http://localhost:7001/eureka/ # 入驻地址
  #      defaultZone: http://eureka7002.com:7002/eureka/, http://eureka7001.com:7001/eureka/   #集群的写法
  instance:
    instance-id: hy-opfe-8100   #服务名称
    prefer-ip-address: true #显示访问路径的ip地址

feign:
  hystrix:
    enabled: true # 在Feign中开启Hystrix

logging:
  level:
    # feign 日志以什么级别监控哪个接口
    org.xupeng.server.SendMessServer: debug


ribbon:
  ReadTimeout: 10000
  ConnectTimeout: 10000

