
server:
  port: 9010

spring:
  application:
    name: commons-api-openfeign

  cloud:
    nacos:
      discovery:
        server-addr: 120.77.255.131:8848




#hystrix的超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 30000
#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
